app6.0/myApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myGroups.urls")),
]

app6.0/myGroups/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index),
    path("grupos", views.groupsMenu, name="groups_home"),
    path("grupos/nuevo/", views.newGroup),
    path("grupos/editar/<str:pk>/", views.updateGroup, name="grupos_editar"),
    path("grupos/eliminar/<str:pk>/", views.deleteGroup, name="grupos_eliminar"),
    path("grupos/nuevo/alumnos/", views.newStudent, name="alumno_nuevo"),
    path("grupos/lista/<str:pk>", views.groupList, name="grupo_lista"),
]

app6.0/myGroups/models.py
from django.db import models


class Groups(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Students(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    second_last_name = models.CharField(max_length=50)
    group = models.ForeignKey(Groups, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

app6.0/myGroups/forms.py
from django import forms
from django.forms import ModelForm

from .models import Groups, Students


class GroupForm(forms.ModelForm):
    class Meta:
        model = Groups
        fields = "__all__"
        labels = {
            "name": "Ingresa grupo y grado"
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control col-sm-4"}),
        }


class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = "__all__"
        labels = {
            "name": "Nombre/s",
            "last_name": "Apellido Paterno",
            "second_last_name": "Apellido Materno",
            "group": "Grupo",
        }

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control col-lg-4"}),
            "last_name": forms.TextInput(attrs={"class": "form-control col-lg-4"}),
            "second_last_name": forms.TextInput(attrs={"class": "form-control col-lg-4"}),
            "group": forms.Select(attrs={"class": "form-control col-lg-4"}),
        }

app6.0/myGroups/views.py
from django.shortcuts import render, redirect
from django.forms import modelformset_factory
from .models import Groups, Students
from .forms import StudentsForm, GroupForm
from django.contrib import messages


def index(request):
    return render(request, "base.html")


def groupsMenu(request):
    grupos = Groups.objects.all()
    return render(request, "groups.html", {"grupos": grupos})


def newGroup(request):
    form = GroupForm()
    if request.method == "POST":

        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/grupos") # /grupos/nuevo/lista
    context = {"form": form}
    return render(request, "new_group.html", context)


def updateGroup(request, pk):
    grupo = Groups.objects.get(id=pk)
    form = GroupForm(instance=grupo)
    if request.method == "POST":

        form = GroupForm(request.POST, instance=grupo)
        if form.is_valid():
            form.save()
            return redirect("/grupos")

    context = {"form": form}
    return render(request, "new_group.html", context)


def deleteGroup(request, pk):
    grupo = Groups.objects.get(id=pk)
    if request.method == "POST":
        grupo.delete()
        return redirect("/grupos")
    context = {"grupo": grupo}
    return render(request, "delete_group.html", context)


def newStudent(request):
    form = StudentsForm()
    if request.method == "POST":
        form = StudentsForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Alumno agregado exitosamente! Puedes seguir agregando más alumnos.')
            return redirect("/grupos/nuevo/alumnos/") # /grupos/nuevo/alumnos

    alumnos = Students.objects.all()
    context = {"form": form, "alumnos": alumnos}
    return render(request, "new_list.html", context)


def groupList(request, pk):
    grupo = Groups.objects.get(id=pk)
    alumnos = Students.objects.filter(group=grupo).order_by("last_name")
    return render(request, "group_list.html", {"alumnos": alumnos, "grupo": grupo})

app6.0/myGroups/templates/base.html
{% load static %}
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Admin profes</title>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

  </head>


  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="/">Nombre/logo</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Cerrar sesión</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="/">
              <span data-feather="home"></span>
              Inicio <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/grupos">
              <span data-feather="file"></span>
              Mis grupos
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
            Tomar asistencia
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Evaluaciones
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Opción 4
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Configuración
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Inicio</h1>
      </div>


        {% block content %}

        {% endblock %}

    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>


  </body>
</html>

app6.0/myGroups/templates/delete_group.html
{% extends "base.html" %}

{% block content %}

<p class="lead">¿Estás seguro que deseas eliminar el grupo "{{grupo}}"?</p>

<form action="{% url 'grupos_eliminar' grupo.id %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'groups_home' %}">Cancelar</a>
    <input type="submit" name="Eliminar grupo" value="Eliminar" class="btn btn-danger">

</form>
{% endblock %}

app6.0/myGroups/templates/group_list.html
{% extends "base.html" %}

{% block content %}

<h3>Lista de alumnos de {{ grupo.name }} </h3>
<a href="/grupos/nuevo/alumnos/" class="btn btn-primary btn-lista">Agregar alumnos</a>

<table class="table table-striped">
    <thead>
<tr>
    <th scope="col">Nombre/s</th>
    <th scope="col">Apellido Paterno</th>
    <th scope="col">Apellido Materno</th>
  </tr>
</thead>
    <tbody>
{% for alumno in alumnos %}
<tr>
    <th scope="row">{{ alumno.name|capfirst }}</th>
    <td>{{ alumno.last_name|capfirst }}</td>
    <td>{{ alumno.second_last_name|capfirst }}</td>
  </tr>
{% endfor %}

<tbody>
</table>
{% endblock %}

app6.0/myGroups/templates/groups.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<h3>Lista de grupos</h3>

<a href="grupos/nuevo" class="btn btn-primary">Crear grupo nuevo</a>

  <div class="row groups-wraper">
      {% for grupo in grupos %}
        <div class="col-sm-4">
          <div class="card">
            <div class="card-header">
                Grupo: {{ grupo.name }}
            </div>

            <img src="{% static "img/img1.png" %}" class="card-img-top" alt="...">
            <div class="card-body">

              <p class="card-text">Alumnos: {{ grupo.students_set.count }}</p>
              <a href="{% url 'grupo_lista' grupo.id %}" class="btn btn-primary">Entrar al grupo</a>
              <a href="{% url 'grupos_editar' grupo.id %}" class="btn btn-primary">Editar</a>
              <a href="{% url 'grupos_eliminar' grupo.id %}" class="btn btn-danger">Eliminar</a>
            </div>
          </div>
        </div>
      {% endfor %}
  </div>

{% endblock %}

app6.0/myGroups/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app6.0/myGroups/templates/new_group.html
{% extends "base.html" %}

{% block content %}

      <div class="row new-group-wraper">


        <form id="new-group-form" method="POST" action="">

            {% csrf_token %}

          {{form.as_p}}
          <input type="submit" class="btn btn-primary" name="Crear grupo" value="Aceptar">

        </form>


      </div>
{% endblock %}

app6.0/myGroups/templates/new_list.html
{% extends "base.html" %}

{% block content %}

<form id="add-list-form" method="POST" action="">

            {% csrf_token %}


            {{ form.as_p }}

          <input type="submit" class="btn btn-primary" name="Agregar lista" value="Agregar alumno">

        </form>

{% if messages %}
<div class="messages alert alert-success">
    {% for message in messages %}
    <h5 {% if message.tags %} class=" {{ message.tags }} alert-heading" {% endif %}> {{ message }} </h5>
    {% endfor %}
</div>
{% endif %}

<a href="/grupos" class="btn btn-secondary">¡Listo!</a>

{% endblock %}